#!/usr/bin/env python3
"""Evaluate the frozen synthetic-trained model on the tabletop fixture.

This is a feature-scarce transfer check on a seeded synthetic stand-in, not a
physical rig result. It does not train on the fixture or read the locked test.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import yaml

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from scripts.final_eval import _calibrate, _class_metrics, _threshold_predictions
from scripts.run_domain_gap_stage2 import (
    BRIDGE_CHANNELS,
    RAW_LOG,
    WINDOWED_REF,
    bridge_raw_to_series,
    reference_state_at_windows,
)
from src.features.group_a_physical import emit_group_a
from src.features.group_b_temporal import emit_group_b
from src.features.windowing import build_windows
from src.risk.artifacts import load_model_artifact
from src.evaluation.tabletop_protocol import displacement_error_vs_reference

CLASSES = ("NORMAL", "WARNING", "CRITICAL")


def main() -> int:
    raw = pd.read_csv(RAW_LOG)
    ref = pd.read_csv(WINDOWED_REF)
    series = bridge_raw_to_series(raw)
    windows = build_windows(series, channels=BRIDGE_CHANNELS, labels=()).df
    window_ref = reference_state_at_windows(windows, ref)
    # Match reference values onto the physical-window rows before features are
    # emitted; labels and mechanism truth never enter the model input columns.
    ga = emit_group_a(window_ref)
    gb = emit_group_b(window_ref)
    keys = ["event_id", "node_id", "window_index"]
    feature_cols = [c for c in gb.columns if c not in ga.columns or c in keys]
    features = ga.merge(gb[feature_cols], on=keys, how="inner", validate="one_to_one")
    ref_cols = [*keys, "known_displacement_mm", "severity_class"]
    features = features.merge(window_ref[ref_cols], on=keys, how="left", validate="one_to_one")
    matched = features.known_displacement_mm.notna()
    n_bridged, n_matched = len(features), int(matched.sum())
    data = features.loc[matched].reset_index(drop=True)
    y = np.where(data.severity_class.to_numpy(dtype=float) >= 3, "CRITICAL",
                 np.where(data.severity_class.to_numpy(dtype=float) >= 1, "WARNING", "NORMAL"))

    artifact = load_model_artifact(ROOT / "models/tuned/risk_xgboost_tuned.joblib", expected_schema_version="v2")
    model_features = list(artifact["features"])
    missing = [c for c in model_features if c not in data.columns]
    model_input = data.reindex(columns=[*data.columns, *missing]).copy()
    model_input[missing] = np.nan
    raw_prob = np.zeros((len(data), len(CLASSES)), dtype=float)
    unaligned = artifact["model"].predict_proba(artifact["transform"](model_input).to_numpy(dtype=float))
    for j, class_id in enumerate(artifact["model"].classes_):
        raw_prob[:, int(class_id)] = unaligned[:, j]
    extras = artifact.get("extras", {})
    calibration = extras.get("calibration")
    prob = _calibrate(raw_prob, calibration) if calibration else raw_prob
    params = yaml.safe_load((ROOT / "configs/model_params.yaml").read_text(encoding="utf-8"))
    pred = _threshold_predictions(prob, params["risk_classifier"]["thresholds"])
    metrics = _class_metrics(y, prob, pred)

    per_trial = {}
    for trial, group in data.assign(reference=y, predicted=pred).groupby("event_id", sort=True):
        per_trial[str(trial)] = {
            "windows": int(len(group)),
            "accuracy": float((group.reference == group.predicted).mean()),
            "reference_state_counts": group.reference.value_counts().to_dict(),
            "predicted_state_counts": group.predicted.value_counts().to_dict(),
        }
    active = data[data.node_id.isin(("N2", "N3"))]
    displacement_error = {}
    if not active.empty:
        err = active[["displacement_mean", "known_displacement_mm"]].rename(
            columns={"displacement_mean": "displacement_mm"}
        ).dropna()
        if not err.empty:
            displacement_error = displacement_error_vs_reference(err.assign(node_id="active"), nodes=("active",))

    result = {
        "metadata": {
            "status": "executed_on_seeded_synthetic_fixture; physical_hardware_validation_pending",
            "fixture_provenance": "data/recorded/tabletop; seeded fixture generated by scripts/generate_tabletop_dataset.py",
            "model": "frozen tuned v2 XGBoost; no tabletop retraining",
            "test_set_touched": False,
            "window_count": {"bridged": n_bridged, "reference_matched": n_matched,
                             "unmatched_excluded": n_bridged - n_matched},
            "model_features": model_features,
            "missing_features_passed_as_nan": missing,
            "feature_inputs": "observable Group A/B bridge; labels and mechanism truth kept outside model inputs",
        },
        "risk_state_metrics": metrics,
        "displacement_error": displacement_error,
        "per_trial": per_trial,
    }
    out = ROOT / "experiments/domain_gap_stage2.json"
    out.write_text(json.dumps(result, indent=2, default=float) + "\n", encoding="utf-8")
    report = [
        "# Tabletop domain-gap check", "",
        "This check uses the seeded synthetic stand-in fixture in `data/recorded/tabletop`; it is not a physical rig or real-mine result.",
        "The frozen tuned model was applied without retraining. The tabletop fixture lacks several training inputs, which were passed as NaN.", "",
        f"Matched windows: {n_matched}; unmatched windows excluded: {n_bridged - n_matched}.",
        f"Model inputs absent from the fixture: {', '.join(missing) if missing else 'none'}.", "",
        "## Risk-state metrics", "",
        f"Macro PR-AUC: {metrics['pr_auc_macro_ovr']:.4f}",
        f"Macro F1: {metrics['f1_macro']:.4f}",
        f"CRITICAL recall: {metrics['recall_critical']:.4f}", "",
        "These values describe feature-scarce transfer to a synthetic fixture only. Physical tabletop validation remains pending.", "",
    ]
    (ROOT / "reports/domain_gap.md").write_text("\n".join(report), encoding="utf-8")
    print(json.dumps({"matched_windows": n_matched, "missing_features": missing,
                      "macro_f1": metrics["f1_macro"], "critical_recall": metrics["recall_critical"]}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
